In [1]:
import numpy as np

Вводим матрицу стоимостей разрезов

In [2]:
d = """0 0 8 10 15 10 6 9 0
0 0 0 16 9 8 5 8 6
8 0 0 0 17 4 8 14 8
10 16 0 0 0 8 5 7 16
15 9 17 0 0 0 5 8 10
10 8 14 8 0 0 0 12 6
6 5 8 5 5 0 0 0 17
9 8 4 7 8 12 0 0 0
0 6 8 16 10 6 17 0 0""".split('\n')
d = np.array([list(map(int, i.split())) for i in d])
d

array([[ 0,  0,  8, 10, 15, 10,  6,  9,  0],
       [ 0,  0,  0, 16,  9,  8,  5,  8,  6],
       [ 8,  0,  0,  0, 17,  4,  8, 14,  8],
       [10, 16,  0,  0,  0,  8,  5,  7, 16],
       [15,  9, 17,  0,  0,  0,  5,  8, 10],
       [10,  8, 14,  8,  0,  0,  0, 12,  6],
       [ 6,  5,  8,  5,  5,  0,  0,  0, 17],
       [ 9,  8,  4,  7,  8, 12,  0,  0,  0],
       [ 0,  6,  8, 16, 10,  6, 17,  0,  0]])

Создаём матрицу значений $\tilde n$

In [3]:
n = -1 * np.ones(shape=d.shape, dtype=int)
n

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1]])

Функция вычисления $\tilde n(k, l)$ при помощи динамического программирования

In [4]:
def calc_n(k, l):
    print(k, l, end='')
    
    # уже вычисленные значения
    if n[k, l] != -1:
        print(" - from memory")
        return n[k, l]
    
    # начальные случаи
    if (l == k + 1) or (l == k + 2):
        print(" - border case")
        n[k, l] = 0
        return 0

    # вычисление значения рекуррентно
    print(" - calculating...")
    n[k, l] = min([calc_n(k, i) + calc_n(i, l) + d[k, i] + d[i, l] for i in range(k+1, l)])
    print(k, l, " - calculated!")
    return n[k, l]

Вычисляем все $\tilde n(k, l)$

In [5]:
print("l k - method")
print("-"*15)
for k in range(len(d)):
    for l in range(k+1, len(d)):
        n[k, l] = calc_n(k, l)
        n[l, k] = n[k, l]
n[np.where(n == -1)] = 0

l k - method
---------------
0 1 - border case
0 2 - border case
0 3 - calculating...
0 1 - from memory
1 3 - border case
0 2 - from memory
2 3 - border case
0 3  - calculated!
0 4 - calculating...
0 1 - from memory
1 4 - calculating...
1 2 - border case
2 4 - border case
1 3 - from memory
3 4 - border case
1 4  - calculated!
0 2 - from memory
2 4 - from memory
0 3 - from memory
3 4 - from memory
0 4  - calculated!
0 5 - calculating...
0 1 - from memory
1 5 - calculating...
1 2 - from memory
2 5 - calculating...
2 3 - from memory
3 5 - border case
2 4 - from memory
4 5 - border case
2 5  - calculated!
1 3 - from memory
3 5 - from memory
1 4 - from memory
4 5 - from memory
1 5  - calculated!
0 2 - from memory
2 5 - from memory
0 3 - from memory
3 5 - from memory
0 4 - from memory
4 5 - from memory
0 5  - calculated!
0 6 - calculating...
0 1 - from memory
1 6 - calculating...
1 2 - from memory
2 6 - calculating...
2 3 - from memory
3 6 - calculating...
3 4 - from memory
4 6 - border case

### Ответ:
Матрица значений $\tilde n$

In [6]:
n

array([[ 0,  0,  0,  8, 18, 20, 23, 29, 37],
       [ 0,  0,  0,  0, 16, 12, 18, 23, 31],
       [ 0,  0,  0,  0,  0,  8, 10, 17, 30],
       [ 8,  0,  0,  0,  0,  0,  5, 10, 17],
       [18, 16,  0,  0,  0,  0,  0,  5, 13],
       [20, 12,  8,  0,  0,  0,  0,  0, 12],
       [23, 18, 10,  5,  0,  0,  0,  0,  0],
       [29, 23, 17, 10,  5,  0,  0,  0,  0],
       [37, 31, 30, 17, 13, 12,  0,  0,  0]])

Минимальная стоимость раскроя:

In [7]:
n[0, 8]

37